In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.ensemble import RandomForestClassifier

In [49]:
df_train = pd.read_csv("D:/Rushikesh/BI Datasets/3 train.csv")
df_test = pd.read_csv("D:/Rushikesh/BI Datasets/3 test.csv")

In [50]:
df_train.head()

,Unnamed: 0,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,...,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at,cancer
0,0,-214,-153,-58,88,-295,-558,199,-176,252,...,511,-125,389,-37,793,329,36,191,-37,0
1,1,-139,-73,-1,283,-264,-400,-330,-168,101,...,837,-36,442,-17,782,295,11,76,-14,0
2,2,-76,-49,-307,309,-376,-650,33,-367,206,...,1199,33,168,52,1138,777,41,228,-41,0
3,3,-135,-114,265,12,-419,-585,158,-253,49,...,835,218,174,-110,627,170,-50,126,-91,0
4,4,-106,-125,-76,168,-230,-284,4,-122,70,...,649,57,504,-26,250,314,14,56,-25,0

In [51]:
df_test.head()

,Unnamed: 0,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,...,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at,cancer
0,0,-342,-200,41,328,-224,-427,-656,-292,137,...,1023,67,214,-135,1074,475,48,168,-70,0
1,1,-87,-248,262,295,-226,-493,367,-452,194,...,529,-295,352,-67,67,263,-33,-33,-21,0
2,2,22,-153,17,276,-211,-250,55,-141,0,...,399,16,558,24,893,297,6,1971,-42,0
3,3,-243,-218,-163,182,-289,-268,-285,-172,52,...,277,6,81,2,722,170,0,510,-73,0
4,4,-130,-177,-28,266,-170,-326,-222,-93,10,...,643,51,450,-46,612,370,29,333,-19,0

In [52]:
df_train.describe()

,Unnamed: 0,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,...,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at,cancer
count,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,...,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000,38.000000
mean,18.500000,-120.868421,-150.526316,-17.157895,181.394737,-276.552632,-439.210526,-43.578947,-201.184211,99.052632,...,750.842105,8.815789,399.131579,-20.052632,869.052632,335.842105,19.210526,504.394737,-29.210526,0.289474
std,11.113055,109.555656,75.734507,117.686144,117.468004,111.004431,135.458412,219.482393,90.838989,83.178397,...,298.008392,77.108507,469.579868,42.346031,482.366461,209.826766,31.158841,728.744405,30.851132,0.459606
min,0.000000,-476.000000,-327.000000,-307.000000,-36.000000,-541.000000,-790.000000,-479.000000,-463.000000,-82.000000,...,224.000000,-178.000000,36.000000,-112.000000,195.000000,41.000000,-50.000000,-2.000000,-94.000000,0.000000
25%,9.250000,-138.750000,-205.000000,-83.250000,81.250000,-374.250000,-547.000000,-169.000000,-239.250000,36.000000,...,575.500000,-42.750000,174.500000,-48.000000,595.250000,232.750000,8.000000,136.000000,-42.750000,0.000000
50%,18.500000,-106.500000,-141.500000,-43.500000,200.000000,-263.000000,-426.500000,-33.500000,-185.500000,99.500000,...,700.000000,10.500000,266.000000,-18.000000,744.500000,308.500000,20.000000,243.500000,-26.000000,0.000000
75%,27.750000,-68.250000,-94.750000,47.250000,279.250000,-188.750000,-344.750000,79.000000,-144.750000,152.250000,...,969.500000,57.000000,451.750000,9.250000,1112.000000,389.500000,30.250000,487.250000,-11.500000,1.000000
max,37.000000,17.000000,-20.000000,265.000000,392.000000,-51.000000,-155.000000,419.000000,-24.000000,283.000000,...,1653.000000,218.000000,2527.000000,52.000000,2315.000000,1109.000000,115.000000,3193.000000,36.000000,1.000000

In [53]:
df_test.describe()

,Unnamed: 0,AFFX-BioB-5_at,AFFX-BioB-M_at,AFFX-BioB-3_at,AFFX-BioC-5_at,AFFX-BioC-3_at,AFFX-BioDn-5_at,AFFX-BioDn-3_at,AFFX-CreX-5_at,AFFX-CreX-3_at,...,U58516_at,U73738_at,X06956_at,X16699_at,X83863_at,Z17240_at,L49218_f_at,M71243_f_at,Z78285_f_at,cancer
count,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,...,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000,34.000000
mean,16.500000,-107.558824,-170.852941,2.088235,198.235294,-227.323529,-347.970588,-88.470588,-178.970588,58.882353,...,576.205882,-34.735294,362.441176,-48.882353,681.647059,268.294118,-1.205882,354.235294,-32.088235,0.411765
std,9.958246,83.662088,115.018347,129.075117,106.335392,130.331215,153.288891,345.372108,109.298447,92.545080,...,291.440599,93.479315,245.543947,58.024950,397.651887,199.751289,54.930689,479.403990,49.030212,0.499554
min,0.000000,-342.000000,-531.000000,-410.000000,9.000000,-535.000000,-810.000000,-1038.000000,-452.000000,-148.000000,...,91.000000,-295.000000,-24.000000,-220.000000,67.000000,-42.000000,-207.000000,-68.000000,-190.000000,0.000000
25%,8.250000,-156.250000,-216.500000,-49.000000,142.000000,-276.500000,-398.500000,-222.000000,-224.750000,-6.000000,...,387.000000,-78.250000,239.250000,-78.000000,427.500000,165.500000,-19.250000,102.250000,-63.500000,0.000000
50%,16.500000,-92.500000,-148.500000,10.000000,177.500000,-208.500000,-309.500000,-95.500000,-141.000000,46.000000,...,557.000000,-9.500000,298.500000,-52.500000,621.500000,241.500000,0.000000,203.000000,-31.500000,0.000000
75%,24.750000,-56.500000,-102.000000,47.500000,274.500000,-170.250000,-246.250000,119.500000,-106.500000,130.000000,...,695.250000,31.000000,459.000000,2.000000,880.000000,366.000000,26.750000,328.500000,-1.250000,1.000000
max,33.000000,86.000000,-13.000000,312.000000,431.000000,114.000000,-122.000000,709.000000,-11.000000,236.000000,...,1455.000000,132.000000,1075.000000,47.000000,1950.000000,906.000000,84.000000,1971.000000,78.000000,1.000000

In [54]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Columns: 7131 entries, Unnamed: 0 to cancer
dtypes: int64(7131)
memory usage: 2.1 MB

In [55]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Columns: 7131 entries, Unnamed: 0 to cancer
dtypes: int64(7131)
memory usage: 1.8 MB

In [56]:
df_train.columns

Index(['Unnamed: 0', 'AFFX-BioB-5_at', 'AFFX-BioB-M_at', 'AFFX-BioB-3_at',
       'AFFX-BioC-5_at', 'AFFX-BioC-3_at', 'AFFX-BioDn-5_at',
       'AFFX-BioDn-3_at', 'AFFX-CreX-5_at', 'AFFX-CreX-3_at',
       ...
       'U58516_at', 'U73738_at', 'X06956_at', 'X16699_at', 'X83863_at',
       'Z17240_at', 'L49218_f_at', 'M71243_f_at', 'Z78285_f_at', 'cancer'],
      dtype='object', length=7131)

In [57]:
df_test.columns

Index(['Unnamed: 0', 'AFFX-BioB-5_at', 'AFFX-BioB-M_at', 'AFFX-BioB-3_at',
       'AFFX-BioC-5_at', 'AFFX-BioC-3_at', 'AFFX-BioDn-5_at',
       'AFFX-BioDn-3_at', 'AFFX-CreX-5_at', 'AFFX-CreX-3_at',
       ...
       'U58516_at', 'U73738_at', 'X06956_at', 'X16699_at', 'X83863_at',
       'Z17240_at', 'L49218_f_at', 'M71243_f_at', 'Z78285_f_at', 'cancer'],
      dtype='object', length=7131)

In [59]:
x_train = df_train.iloc[:,:-1]
y_train = df_train.iloc[:,-1:]
x_test = df_test.iloc[:,:-1]
y_test = df_test.iloc[:,-1:]

In [60]:
model = RandomForestClassifier()
model.fit(x_train,y_train)

C:\Users\user\AppData\Local\Temp\ipykernel_19244\251184282.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x_train,y_train)

RandomForestClassifier()

In [63]:
y_pred=model.predict(x_test)
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy of the model:{accuracy*100}%")

Accuracy of the model:67.64705882352942%

In [64]:
class_report=classification_report(y_test,y_pred)
print(f"Class Report:{class_report}")

Class Report:              precision    recall  f1-score   support

           0       0.65      1.00      0.78        20
           1       1.00      0.21      0.35        14

    accuracy                           0.68        34
   macro avg       0.82      0.61      0.57        34
weighted avg       0.79      0.68      0.61        34